const Pgrup qsm[] = {
	{"***:"," QUITTIERBARE   ","       ", P&Stoermeld,							 ASCII_FORM, 0, P&vis,	V1, 0, 0},
	{"*01:"," QSM VORHANDEN ?","       ", P&un_qsm,			 						JANEIN_FORM, 0, P&vis,	V1, 0, 0},

//**PARSER-BEGIN-qsm[]**  AUTOMATISCHE ERZEUGUNG *****
// Diese Zeilen wurde automatisch am : 21.03.2018 um 10:29:40 generiert und entspricht der Systemversion nach 19.07.2017 10:21:03!!!
// Path: C:\RIEcon36C\Softwarepool\Softwarepool_PES_2018\KE_JMX81\KE_1ss3_JMX81\User\Komtabparser.exe
	{"ANL:"," AUSSENLUFTTEMP.","       ", P&alarmtab[0].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"ANL:"," SMGRUP STANDARD","       ", P&alarmtab[1].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"ANL:"," SMGRUP FUEHLER ","       ", P&alarmtab[2].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"ANL:"," SMGRUP MODULE  ","       ", P&alarmtab[3].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"ANL:"," SSTM PUMPENBUS?","       ", P&alarmtab[4].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"KES:"," VL-KESSEL TVK1 ","       ", P&alarmtab[5].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"KES:"," ANFORDER.EXT 1 ","       ", P&alarmtab[6].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"KES:"," ANFORDER.EXT 2 ","       ", P&alarmtab[7].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"KES:"," SSM KESSEL ?   ","       ", P&alarmtab[8].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"KES:"," HANDBETRIEB ?  ","       ", P&alarmtab[9].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"HK1:"," VL-HEIZUNG  TVH","       ", P&alarmtab[10].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"HK1:"," RL-HEIZUNG  TRH","       ", P&alarmtab[11].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"HK1:"," ANFORDER.EXT 1 ","       ", P&alarmtab[12].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"HK1:"," ANFORDER.EXT 2 ","       ", P&alarmtab[13].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"HK1:"," SM REGELABW.?  ","       ", P&alarmtab[14].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"HK1:"," SM STW H     ? ","       ", P&alarmtab[15].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"HK1:"," SM PU H       ?","       ", P&alarmtab[16].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"HK1:"," HANDBETRIEB ?  ","       ", P&alarmtab[17].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"HKS:"," HANDBETRIEB ?  ","       ", P&alarmtab[18].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"TWE:"," REGELTEMP.  TW1","       ", P&alarmtab[19].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"TWE:"," SPEICHER OB.TW2","       ", P&alarmtab[20].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"TWE:"," SPEICHER MI.TW3","       ", P&alarmtab[21].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"TWE:"," SPEICHER UN.TW4","       ", P&alarmtab[22].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"TWE:"," ZIRK-RUECKL TW5","       ", P&alarmtab[23].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"TWE:"," TWE-RUECKL. TW6","       ", P&alarmtab[24].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"TWE:"," SM REGELABW. ? ","       ", P&alarmtab[25].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"TWE:"," SM STW TWE   ? ","       ", P&alarmtab[26].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"TWE:"," SM PU ZIR    ? ","       ", P&alarmtab[27].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"TWE:"," SM PU TWE     ?","       ", P&alarmtab[28].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"TWE:"," HANDBETRIEB   ?","       ", P&alarmtab[29].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SOL:"," KOLLEKTOR   TS1","       ", P&alarmtab[30].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SOL:"," SOLAR-TWE   TS2","       ", P&alarmtab[31].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SOL:"," SOLAR-HEIZ. TS3","       ", P&alarmtab[32].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SOL:"," SOLAR-PUFF. TS4","       ", P&alarmtab[33].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SOL:"," RL-SOLAR    TS6","       ", P&alarmtab[34].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SOL:"," PUFFERSP TSPo-P","       ", P&alarmtab[35].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SOL:"," PUFFERSP TSPu-P","       ", P&alarmtab[36].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SOL:"," SM DRU.KOL.MAX?","       ", P&alarmtab[37].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SOL:"," SM DRU.KOL.MIN?","       ", P&alarmtab[38].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SOL:"," SM DRU.PUF.MAX?","       ", P&alarmtab[39].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SOL:"," SM DRU.PUF.MIN?","       ", P&alarmtab[40].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SOL:"," VOL.STR. ALARM?","       ", P&alarmtab[41].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SOL:"," TS3 > TS2 ?    ","       ", P&alarmtab[42].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SOL:"," KWZ DEFEKT ?   ","       ", P&alarmtab[43].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SOL:"," SM PU SOL     ?","       ", P&alarmtab[44].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SOL:"," SM PU PK      ?","       ", P&alarmtab[45].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SOL:"," HANDBETRIEB   ?","       ", P&alarmtab[46].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"ZLT;"," OBJ-ORT FEHLT ?","       ", P&alarmtab[47].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"ZLT;"," PIN FEHLT ?    ","       ", P&alarmtab[48].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SYS;"," DAT-ERROR R37_1","       ", P&alarmtab[49].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SYS;"," DAT-ERROR R37_2","       ", P&alarmtab[50].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SYS;"," DAT-ERROR R38_1","       ", P&alarmtab[51].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SYS;"," RTC-UHR ERROR  ","       ", P&alarmtab[52].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SYS;"," MAIN-CRASH:TASK","       ", P&alarmtab[53].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SYS;"," FerroRAM2 FEHLT","       ", P&alarmtab[54].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SYS;"," SDHC-Card FEHLT","       ", P&alarmtab[55].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
//**PARSER-ENDE-qsm[]**  AUTOMATISCHE ERZEUGUNG *****

	{" 99:"," QUITTIER-TASTE "," EIN=1 ", P&quit_taste,			 						US_CHAR, 0, P&hid1,	V1, 0, 0},

};

